export const FETCH_DAILY_TIMESERIES = "dailyTimeSeries/FETCH_DAILY_TIMESERIES";
export const FETCH_DAILY_TIMESERIES_SUCCESS = "dailyTimeSeries/FETCH_DAILY_TIMESERIES_SUCCESS";
export const FETCH_DAILY_TIMESERIES_FAILURE = "dailyTimeSeries/FETCH_DAILY_TIMESERIES_FAILURE";
