export const FETCH_INSTRUMENTS = "instruments/FETCH_INSTRUMENTS";
export const FETCH_INSTRUMENTS_SUCCESS = "instruments/FETCH_INSTRUMENTS_SUCCESS";
export const FETCH_INSTRUMENTS_FAILURE = "instruments/FETCH_INSTRUMENTS_FAILURE";
