export const INSTRUMENT_INTRADAY_TIMESERIES = ({
    FETCH_INSTRUMENT_INTRADAY_TIMESERIES: "FETCH_INSTRUMENT_INTRADAY_TIMESERIES",
    FETCH_INSTRUMENT_INTRADAY_TIMESERIES_SUCCESS: "FETCH_INSTRUMENT_INTRADAY_TIMESERIES_SUCCESS",
    FETCH_INSTRUMENT_INTRADAY_TIMESERIES_FAILURE: "FETCH_INSTRUMENT_INTRADAY_TIMESERIES_FAILURE"
})

export const fetchInstrumentIntradayTimeSeries = instrument => ({
    type: INSTRUMENT_INTRADAY_TIMESERIES.FETCH_INSTRUMENT_INTRADAY_TIMESERIES,
    instrument: instrument
});

export const fetchInstrumentIntradayTimeSeriesSuccess = timeSeries => ({
    type: INSTRUMENT_INTRADAY_TIMESERIES.FETCH_INSTRUMENT_INTRADAY_TIMESERIES_SUCCESS,
    intradayTimeSeries: timeSeries
});

export const fetchInstrumentIntradayTimeSeriesFailure = errorMessage => ({
    type: INSTRUMENT_INTRADAY_TIMESERIES.FETCH_INSTRUMENT_INTRADAY_TIMESERIES_FAILURE,
    error: errorMessage
});
